# apiVersion: v1
# kind: Pod
# metadata:
#   name: hnh-app
#   labels:
#     app: hnh-app # Added this label so Nginx reverse proxy can discover it
# spec:
#   containers:
#     - name: app
#       image: hnh-app:latest
#       imagePullPolicy: IfNotPresent
#       ports:
#         - containerPort: 8090
#       env:
#         - name: SPRING_DATASOURCE_URL
#           value: "jdbc:mysql://mysql-service:3306/heng_nguonhour_db" # Pointing to the internal service name
#         - name: SPRING_DATASOURCE_USERNAME
#           value: "root" # FIX: Wrapped username string in quotes
#         - name: SPRING_DATASOURCE_PASSWORD
#           value: "Hnh00900" # FIX: Wrapped password string in quotes
apiVersion: v1
kind: Pod
metadata:
  name: hnh-system
spec:
  containers:
    # Web container
    - name: web
      image: hnh-app:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8090
        - containerPort: 8443
        - containerPort: 2222

      env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://localhost:3306/heng_nguonhour_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: Hnh00900

    # MySQL container
    - name: mysql
      image: mysql:8
      ports:
        - containerPort: 3306

      env:
        - name: MYSQL_ROOT_PASSWORD
          value: Hnh00900

        - name: MYSQL_DATABASE
          value: heng_nguonhour_db
