name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission
        run: chmod +x hnh/gradlew

      - name: Build
        run: cd hnh && ./gradlew clean build -x test

      - name: Test
        run: cd hnh && ./gradlew test || true

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Deploy
        run: cd hnh && ansible-playbook -i inventory.ini playbook.yml
